import { ProfileItem, ProxyItem } from './types';

export const APP_NAME = "Accsafe";

export const SOCIAL_LINKS = [
  { name: 'Facebook', url: 'https://facebook.com', color: 'bg-blue-600', icon: 'FB' },
  { name: 'Zalo', url: 'https://zalo.me', color: 'bg-blue-500', icon: 'Zalo' },
  { name: 'Telegram', url: 'https://telegram.org', color: 'bg-sky-500', icon: 'TG' },
  { name: 'Instagram', url: 'https://instagram.com', color: 'bg-pink-600', icon: 'IG' }
];

export const AUTOMATION_SCRIPTS = [
  // Social Media
  { id: 'fb-login', name: 'Facebook', url: 'https://facebook.com', icon: 'Facebook', category: 'Social' },
  { id: 'instagram', name: 'Instagram', url: 'https://instagram.com', icon: 'Instagram', category: 'Social' },
  { id: 'twitter', name: 'Twitter/X', url: 'https://twitter.com', icon: 'Twitter', category: 'Social' },
  { id: 'linkedin', name: 'LinkedIn', url: 'https://linkedin.com', icon: 'LinkedIn', category: 'Social' },
  { id: 'tiktok', name: 'TikTok', url: 'https://tiktok.com', icon: 'TikTok', category: 'Social' },
  { id: 'reddit', name: 'Reddit', url: 'https://reddit.com', icon: 'Reddit', category: 'Social' },
  
  // E-commerce
  { id: 'amz-surf', name: 'Amazon', url: 'https://amazon.com', icon: 'ShoppingBag', category: 'Shopping' },
  { id: 'ebay', name: 'eBay', url: 'https://ebay.com', icon: 'ShoppingBag', category: 'Shopping' },
  { id: 'shopify', name: 'Shopify', url: 'https://shopify.com', icon: 'ShoppingBag', category: 'Shopping' },
  { id: 'aliexpress', name: 'AliExpress', url: 'https://aliexpress.com', icon: 'ShoppingBag', category: 'Shopping' },
  
  // Search & Tools
  { id: 'google-farm', name: 'Google', url: 'https://google.com', icon: 'Chrome', category: 'Search' },
  { id: 'bing', name: 'Bing', url: 'https://bing.com', icon: 'Chrome', category: 'Search' },
  { id: 'duckduckgo', name: 'DuckDuckGo', url: 'https://duckduckgo.com', icon: 'Chrome', category: 'Search' },
  
  // Entertainment
  { id: 'yt-watch', name: 'YouTube', url: 'https://youtube.com', icon: 'Youtube', category: 'Entertainment' },
  { id: 'netflix', name: 'Netflix', url: 'https://netflix.com', icon: 'Youtube', category: 'Entertainment' },
  { id: 'spotify', name: 'Spotify', url: 'https://spotify.com', icon: 'Youtube', category: 'Entertainment' },
  { id: 'twitch', name: 'Twitch', url: 'https://twitch.tv', icon: 'Youtube', category: 'Entertainment' },
  
  // News & Media
  { id: 'cnn', name: 'CNN', url: 'https://cnn.com', icon: 'Chrome', category: 'News' },
  { id: 'bbc', name: 'BBC', url: 'https://bbc.com', icon: 'Chrome', category: 'News' },
  { id: 'nytimes', name: 'New York Times', url: 'https://nytimes.com', icon: 'Chrome', category: 'News' },
  
  // Banking & Finance
  { id: 'paypal', name: 'PayPal', url: 'https://paypal.com', icon: 'ShoppingBag', category: 'Finance' },
  { id: 'stripe', name: 'Stripe', url: 'https://stripe.com', icon: 'ShoppingBag', category: 'Finance' },
  
  // Development
  { id: 'github', name: 'GitHub', url: 'https://github.com', icon: 'Chrome', category: 'Dev' },
  { id: 'stackoverflow', name: 'Stack Overflow', url: 'https://stackoverflow.com', icon: 'Chrome', category: 'Dev' },
];

export const CPU_OPTIONS = [2, 4, 8, 16, 32];
export const RAM_OPTIONS = [4, 8, 16, 32, 64];
export const RESOLUTION_OPTIONS = [
  "1920x1080",
  "1366x768",
  "1440x900",
  "2560x1440",
  "2560x1600",
  "3840x2160"
];

export const TRANSLATIONS = {
  en: {
    login: "Login",
    register: "Register",
    logout: "Logout",
    dashboard: "Dashboard",
    profiles: "Profiles",
    proxies: "Proxies",
    automation: "Automation",
    support: "Support",
    settings: "Settings",
    createProfile: "Create Profile",
    addProxy: "Add Proxy",
    open: "Open",
    stop: "Stop",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirmLogout: "Are you sure you want to logout?",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    orLoginWith: "Or login with",
    profileName: "Profile Name",
    deviceType: "Device Type",
    proxy: "Proxy",
    hardware: "Hardware",
    advanced: "Advanced",
    overview: "Overview",
    browser: "Browser",
    os: "Operating System",
    userAgent: "User Agent",
    generate: "Generate",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark Mode",
    changePassword: "Change Password",
    oldPassword: "Old Password",
    newPassword: "New Password",
    contact: "Contact Channels",
    docs: "Documentation",
    docsWelcome: "Welcome to the Accsafe documentation. This guide will help you manage your browser profiles securely.",
    docsGettingStarted: "Getting Started",
    docsGettingStarted1: "Create a new profile by clicking the \"+\" button in the dashboard.",
    docsGettingStarted2: "Configure your hardware fingerprints in the \"Hardware\" tab.",
    docsGettingStarted3: "Assign a proxy to ensure your IP address is masked.",
    docsTroubleshooting: "Troubleshooting",
    docsTroubleshooting1: "If a profile fails to open, check if the proxy status is active. You can re-check proxies in the Proxy Manager.",
    noProfiles: "No profiles found. Create one to get started.",
    noProxies: "No proxies found.",
    running: "Running",
    stopped: "Stopped",
    success: "Success",
    error: "Error",
    savedSuccessfully: "Saved successfully!",
    deletedSuccessfully: "Deleted successfully!",
    passwordChanged: "Password changed successfully!",
    passwordMismatch: "Old password is incorrect!",
    confirmDelete: "Are you sure you want to delete this?",
    supportChat: "Chat with us",
    cpuCores: "CPU Cores",
    memory: "Memory (RAM)",
    screenRes: "Screen Resolution",
    gpu: "Graphics Card (GPU Masking)",
    canvasNoise: "Canvas Noise",
    audioNoise: "AudioContext Noise",
    webrtc: "WebRTC Policy",
    advancedWarn: "Advanced Fingerprinting",
    advancedWarnDesc: "Changing these settings may affect browser stability or detectability.",
    adminPanel: "Admin Panel",
    typeMessage: "Type a message...",
    send: "Send",
    noChats: "No active conversations.",
    chatHistory: "Chat History",
    clearChat: "Clear Chat",
    clearChatConfirm: "Are you sure you want to clear this conversation history?",
    deleteChat: "Delete Conversation",
    deleteChatConfirm: "Are you sure you want to delete this conversation? This cannot be undone.",
    admin: "Administrator",
    profileStarting: "Profile is starting...",
    profileStopped: "Profile stopped",
    profileAlreadyRunning: "Profile is already running",
    profileNotRunning: "Profile is not running",
    profileNotFound: "Profile not found",
    proxyNotFound: "Proxy not found",
    cannotDeleteProxy: "Cannot delete proxy",
    cannotUpdateProfileStatus: "Cannot update profile status",
    cannotCreateProfile: "Cannot create profile",
    cannotDeleteProfile: "Cannot delete profile",
    electronNotAvailable: "Electron is not available. Please run the app in Electron.",
    pleaseLoginToCreateProfile: "Please login to create profile",
    ipAndPortRequired: "IP and Port are required",
    userManagement: "User Management",
    totalUsers: "Total: {count} users ({regular} regular, {admin} admin)",
    regularUsers: "Regular Users",
    adminUsers: "Administrators",
    name: "Name",
    createdAt: "Created Date",
    actions: "Actions",
    role: "Role",
    deleteUser: "Delete User",
    confirmDeleteUser: "Are you sure you want to delete user {email}?",
    deleteUserWarning: "This action will delete all profiles, proxies and chat sessions of this user. This action cannot be undone.",
    userDeletedSuccess: "User deleted successfully",
    cannotLoadUsers: "Cannot load users list",
    cannotDeleteUser: "Cannot delete user",
    loadingUsers: "Loading users list...",
    noUsers: "No users yet",
    refresh: "Refresh",
    loading: "Loading...",
    sessionExpired: "Session expired. Please login again.",
    noPermission: "You do not have permission. Only admins can view the user list.",
    errorLoadingUsers: "Error loading users: {status}",
    cannotGetUsers: "Cannot get users list",
    cannotDeleteUserError: "Cannot delete user",
    cannotDeleteAdmin: "Cannot delete admin account"
  },
  vi: {
    login: "Đăng nhập",
    register: "Đăng ký",
    logout: "Đăng xuất",
    dashboard: "Tổng quan",
    profiles: "Quản lý Hồ sơ",
    proxies: "Quản lý Proxy",
    automation: "Tự động hóa",
    support: "Hỗ trợ",
    settings: "Cài đặt",
    createProfile: "Tạo Hồ sơ",
    addProxy: "Thêm Proxy",
    open: "Mở",
    stop: "Dừng",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    cancel: "Hủy",
    confirmLogout: "Bạn có chắc chắn muốn đăng xuất?",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    orLoginWith: "Hoặc đăng nhập với",
    profileName: "Tên hồ sơ",
    deviceType: "Loại thiết bị",
    proxy: "Máy chủ Proxy",
    hardware: "Phần cứng",
    advanced: "Nâng cao",
    overview: "Tổng quan",
    browser: "Trình duyệt",
    os: "Hệ điều hành",
    userAgent: "User Agent",
    generate: "Tạo ngẫu nhiên",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    darkMode: "Chế độ tối",
    changePassword: "Đổi mật khẩu",
    oldPassword: "Mật khẩu cũ",
    newPassword: "Mật khẩu mới",
    contact: "Kênh hỗ trợ",
    docs: "Tài liệu hướng dẫn",
    docsWelcome: "Chào mừng đến với tài liệu hướng dẫn Accsafe. Hướng dẫn này sẽ giúp bạn quản lý các hồ sơ trình duyệt một cách an toàn.",
    docsGettingStarted: "Bắt đầu",
    docsGettingStarted1: "Tạo hồ sơ mới bằng cách nhấp vào nút \"+\" trong bảng điều khiển.",
    docsGettingStarted2: "Cấu hình dấu vân tay phần cứng của bạn trong tab \"Phần cứng\".",
    docsGettingStarted3: "Gán proxy để đảm bảo địa chỉ IP của bạn được ẩn.",
    docsTroubleshooting: "Khắc phục sự cố",
    docsTroubleshooting1: "Nếu hồ sơ không mở được, hãy kiểm tra xem trạng thái proxy có đang hoạt động không. Bạn có thể kiểm tra lại proxy trong Trình quản lý Proxy.",
    noProfiles: "Chưa có hồ sơ nào. Hãy tạo mới.",
    noProxies: "Chưa có proxy nào.",
    running: "Đang chạy",
    stopped: "Đã dừng",
    success: "Thành công",
    error: "Lỗi",
    savedSuccessfully: "Đã lưu thành công!",
    deletedSuccessfully: "Đã xóa thành công!",
    passwordChanged: "Đổi mật khẩu thành công!",
    passwordMismatch: "Mật khẩu cũ không đúng!",
    confirmDelete: "Bạn có chắc chắn muốn xóa mục này không?",
    supportChat: "Chat với chúng tôi",
    cpuCores: "Số nhân CPU",
    memory: "Bộ nhớ (RAM)",
    screenRes: "Độ phân giải màn hình",
    gpu: "Card đồ họa (GPU)",
    canvasNoise: "Nhiễu Canvas",
    audioNoise: "Nhiễu Âm thanh (AudioContext)",
    webrtc: "Chính sách WebRTC",
    advancedWarn: "Cấu hình vân tay nâng cao",
    advancedWarnDesc: "Thay đổi các cài đặt này có thể ảnh hưởng đến độ ổn định của trình duyệt hoặc khả năng bị phát hiện.",
    adminPanel: "Trang Quản Trị",
    typeMessage: "Nhập tin nhắn...",
    send: "Gửi",
    noChats: "Không có cuộc trò chuyện nào.",
    chatHistory: "Lịch sử Chat",
    clearChat: "Làm mới cuộc trò chuyện",
    clearChatConfirm: "Bạn có chắc chắn muốn xóa toàn bộ lịch sử trò chuyện này không?",
    deleteChat: "Xóa cuộc trò chuyện",
    deleteChatConfirm: "Bạn có chắc chắn muốn xóa cuộc trò chuyện này? Hành động này không thể hoàn tác.",
    admin: "Quản trị viên",
    profileStarting: "Profile đang khởi động...",
    profileStopped: "Profile đã dừng",
    profileAlreadyRunning: "Profile đã đang chạy",
    profileNotRunning: "Profile không đang chạy",
    profileNotFound: "Không tìm thấy profile",
    proxyNotFound: "Không tìm thấy proxy",
    cannotDeleteProxy: "Không thể xóa proxy",
    cannotUpdateProfileStatus: "Không thể cập nhật trạng thái profile",
    cannotCreateProfile: "Không thể tạo profile",
    cannotDeleteProfile: "Không thể xóa profile",
    electronNotAvailable: "Electron không khả dụng. Vui lòng chạy app trong Electron.",
    pleaseLoginToCreateProfile: "Vui lòng đăng nhập để tạo profile",
    ipAndPortRequired: "IP và Port là bắt buộc",
    cannotLoadProfiles: "Không thể tải profiles",
    cannotLoadProxies: "Không thể tải proxies",
    userManagement: "Quản Lý Người Dùng",
    totalUsers: "Tổng số: {count} users ({regular} thường, {admin} admin)",
    regularUsers: "Users Thường",
    adminUsers: "Admin",
    name: "Tên",
    createdAt: "Ngày tạo",
    actions: "Thao tác",
    role: "Vai trò",
    deleteUser: "Xóa user",
    confirmDeleteUser: "Bạn có chắc chắn muốn xóa user {email}?",
    deleteUserWarning: "Hành động này sẽ xóa tất cả profiles, proxies và chat sessions của user này. Hành động này không thể hoàn tác.",
    userDeletedSuccess: "Đã xóa user thành công",
    cannotLoadUsers: "Không thể tải danh sách users",
    cannotDeleteUser: "Không thể xóa user",
    loadingUsers: "Đang tải danh sách users...",
    noUsers: "Chưa có users nào",
    refresh: "Làm mới",
    loading: "Đang tải...",
    sessionExpired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    noPermission: "Bạn không có quyền truy cập. Chỉ admin mới có quyền xem danh sách users.",
    errorLoadingUsers: "Lỗi khi lấy danh sách users: {status}",
    cannotGetUsers: "Không thể lấy danh sách users",
    cannotDeleteUserError: "Không thể xóa user",
    cannotDeleteAdmin: "Không thể xóa tài khoản admin"
  }
};

export const MOCK_USER_AGENTS = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
];

export const MOCK_GPUS = [
  "NVIDIA GeForce RTX 3060",
  "NVIDIA GeForce RTX 4090",
  "NVIDIA GeForce GTX 5060",
  "AMD Radeon RX 6700 XT",
  "AMD Radeon RX 7800 XT",
  "Intel Iris Xe Graphics",
  "Intel Arc A770",
  "Apple M1",
  "Apple M2 Pro",
  "NVIDIA GeForce RTX 4070",
  "AMD Radeon RX 6600 XT",
  "NVIDIA GeForce RTX 3080"
];